# About
This notebook contains examples pertaining to matrix operations using numpy.

In [86]:
import numpy as np
import numpy.linalg as LA

# Matrix Instantiation
Creating matrices using numpy

In [87]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(m1)
print(f'shape: {m1.shape}')

print('-' * 20)

m2 = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(m2)
print(f'shape: {m2.shape}')

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
--------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
shape: (2, 3, 2)


In [88]:
z = np.zeros((3, 4))
print(z)
print(f'shape: {z.shape}')

print('-' * 20)

o = np.ones((2, 2, 2))
print(o)
print(f'shape: {o.shape}')

print('-' * 20)

r = np.random.rand(5, 5)  # uniform values between [0, 1)
print(r)
print(f'shape: {r.shape}')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)
--------------------
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
shape: (2, 2, 2)
--------------------
[[0.44374425 0.97403748 0.53169876 0.28616499 0.39609017]
 [0.11284562 0.00127377 0.49212893 0.8136422  0.99825668]
 [0.2924935  0.14824777 0.12746182 0.38614188 0.27206955]
 [0.3562793  0.69752961 0.63498452 0.03523384 0.21965616]
 [0.7434812  0.5629264  0.70785456 0.31654599 0.27934577]]
shape: (5, 5)


In [92]:
# reshaping matrices
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(f'shape: {a.shape}')

print('-' * 20)

a = a.reshape((4, 3))
print(a)
print(f'shape: {a.shape}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)
--------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3)


In [93]:
# adding another dimension to a matrix
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

e = np.expand_dims(a, axis=1)
print(e)
print(f'shape: {e.shape}')

print('-' * 20)

e = np.expand_dims(a, axis=2)
print(e)
print(f'shape: {e.shape}')

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
shape: (3, 1, 4)
--------------------
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
shape: (3, 4, 1)


# Accessing Matrix Elements
Can access matrix elements in a variety of ways:
* by index
* slicing
* using mask arrays/matrices/functions

In [94]:
# by index
m2 = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

print(m2[0])
print(m2[0][1])
print(m2[0][1][0])

[[1 2]
 [3 4]
 [5 6]]
[3 4]
3


In [95]:
# using slices - notation is [start:stop:step]
a = np.array([i for i in range(1, 101)])
a = a.reshape((10, 10))
print(a)

print('-' * 20)

print(a[2:4])  # grab rows 2 and 3

print('-' * 20)

print(a[:, 2:4])  # grab columns 2 and 3

print('-' * 20)

print(a[:, 1::2])  # grab all of the even numbers

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
--------------------
[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]
--------------------
[[ 3  4]
 [13 14]
 [23 24]
 [33 34]
 [43 44]
 [53 54]
 [63 64]
 [73 74]
 [83 84]
 [93 94]]
--------------------
[[  2   4   6   8  10]
 [ 12  14  16  18  20]
 [ 22  24  26  28  30]
 [ 32  34  36  38  40]
 [ 42  44  46  48  50]
 [ 52  54  56  58  60]
 [ 62  64  66  68  70]
 [ 72  74  76  78  80]
 [ 82  84  86  88  90]
 [ 92  94  96  98 100]]


In [96]:
# mask arrays
a = np.array([i for i in range(1, 101)])
a = a.reshape((10, 10))

mask = a % 2 == 0
print(mask)
print(a[mask])

print('-' * 20)

r = a[a % 2 == 0]  # shorthand example of the above
print(r)

[[False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
--------------------
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  7

## Scalar Multiplication
Multiplying a matrix by a scalar value

In [97]:
m = np.array([[1, 2], [3, 4]])
print(m)
print('-' * 20)
print(3 * m)
print('-' * 20)
print(-2 * m)

[[1 2]
 [3 4]]
--------------------
[[ 3  6]
 [ 9 12]]
--------------------
[[-2 -4]
 [-6 -8]]


# Matrix Addition, Subtraction, and Multiplication
Elementwise addition and substraction operations.  Note that for elementwise operations to work the matrices must be the same size!

In [98]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 5], [5, 5]])

print(a + b)

print('-' * 20)

print(a - b)
print(b - a)

print('-' * 20)

print(a * b)

[[6 7]
 [8 9]]
--------------------
[[-4 -3]
 [-2 -1]]
[[4 3]
 [2 1]]
--------------------
[[ 5 10]
 [15 20]]


# Matrix Multiplication
Generally when people refer to matrix multiplication they are referring to the dot product-ish operation not the elementwise multiplication operation.
Calculating the multiplication product for a matrix is basically the dot product that we did for vectors just repeated for every element.



In [102]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 1], [5, 2]])

print(np.matmul(a, b))

[[15  5]
 [35 11]]


In [106]:
a = np.array([[17, 25, 6, 2], [6, 1, 97, 4], [80, 8, 54, 15]])
b = np.array([[3, 14, 1, 7, 42, 5], [32, 11, 2, 4, 18, 17], [19, 81, 4, 8, 5, 10], [27, 2, 3, 6, 7, 3]])

print(f'a: {a.shape} b: {b.shape}')
r = np.matmul(a, b)
print(r)
print(f'{r.shape}')

a: (3, 4) b: (4, 6)
[[1019 1003   97  279 1208  576]
 [2001 7960  408  846  783 1029]
 [1927 5612  357 1114 3879 1121]]
(3, 6)


# Miscellaneous Matrix Information
* transpose of a matrix
* identity matrix
* inverse of a matrix

In [107]:
# transpose
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print('-' * 20)
print(np.transpose(a))
print('-' * 20)
print(a.T)
print('-' * 20)
a = a.reshape((2, 3, 2))
print(a)
print('-' * 20)
a = np.transpose(a, (1, 0, 2))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
--------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
--------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
--------------------
[[[ 1  2]
  [ 7  8]]

 [[ 3  4]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]


In [108]:
# identity matrix
i = np.identity(11)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [109]:
# inverse of a matrix
a = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
a_inv = LA.inv(a)
print(a_inv)
print(np.matmul(a, a_inv))

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
