# About
This notebook contains examples pertaining to matrix operations using numpy.

In [1]:
import numpy as np

# Matrix Instantiation
Creating matrices using numpy

In [6]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(m1)

print('-' * 20)

m2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(m2)

[[1 2 3]
 [4 5 6]]
--------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
print(m1[0][0])
print(m2[0])
print(m2[0][1])
print(m2[0][1][0])

1
[[1 2]
 [3 4]]
[3 4]
3


# Scalar Multiplication
Multiplying a matrix by a scalar value

In [13]:
m = np.array([[1, 2], [3, 4]])
print(m)
print('-' * 20)
print(3 * m)
print('-' * 20)
print(-2 * m)

[[1 2]
 [3 4]]
--------------------
[[ 3  6]
 [ 9 12]]
--------------------
[[-2 -4]
 [-6 -8]]


# Matrix Addition, Subtraction, and Multiplication
Elementwise addition and substraction operations.  Note that for elementwise operations to work the matrices must be the same size!