# About
This notebook contains examples pertaining to the Vector subsection of the linear algebra refresher slide deck.

In [51]:
from timeit import Timer

import numpy as np
import numpy.linalg as LA

# Representation
Representing a single vector in numpy.

In [53]:
v = np.array([[2], [4]])
print(v)
print(v.shape)
print(' -- OR --')
v = np.array([2, 4])  #  my "preferred" way
print(v)
print(v.shape)

[[2]
 [4]]
(2, 1)
 -- OR --
[2 4]
(2,)


# Operations
There are several basic vector operations.  They are:
* addition
* subtraction
* multiplication
    - scalar
    - vector

This section introduces the concept of vectorization as well.  In this content, vectorization
refers to using numpy's "C" for loops instead of Python for loops which are much, much faster.

In [55]:
def display(op, result):
    print(op)
    print(result)
    print()

# Addition
x = np.array([[1], [2]])
y = np.array([[3], [1]])
print('x + y (loop)')
for px, py in zip([1, 2], [3, 1]):
    print(px + py)
print()
display('x + y (vectorized)', x + y)

# Subtraction
x = np.array([[1], [3]])
y = np.array([[5], [1]])
print('x - y (loop)')
for px, py in zip([1, 2], [3, 1]):
    print(px - py)
print()
display('x - y (vectorized)', x - y)
display('y - x (vectorized)', y - x)  # Note how order matters

# Scalar Multiplication
x = np.array([[1], [3]])
y = np.array([[0], [-2]])
print('2x (loop)')
for px in [1, 3]:
    print(2 * px)
print()
display('2x (vectorized)', 2 * x)
display('-3/2y (vectorized)', (-3 / 2) * y)

# Vector Multiplication
x = np.array([[2], [4], [5]])
y = np.array([[3], [2], [1]])
display('x * y (vectorized)', x * y)
print()

# Vectorization performance difference
test_list = list(range(1000000))
nump_arr = np.array(test_list)

def python_for():
    return [num + 1 for num in test_list]

def numpy_add():
    return nump_arr + 1

py_result = min(Timer(python_for).repeat(10, 10))
np_result = min(Timer(numpy_add).repeat(10, 10))
print(f'Python ran in {py_result*1000:.04}ms and numpy ran in {np_result*1000:.04}ms')
print(f'Using numpy was {(py_result - np_result) / np_result}x faster than pure Python')


x + y (loop)
4
3

x + y (vectorized)
[[4]
 [3]]

x - y (loop)
-2
1

x - y (vectorized)
[[-4]
 [ 2]]

y - x (vectorized)
[[ 4]
 [-2]]

2x (loop)
2
6

2x (vectorized)
[[2]
 [6]]

-3/2y (vectorized)
[[-0.]
 [ 3.]]

x * y (vectorized)
[[6]
 [8]
 [5]]


Python ran in 780.8ms and numpy ran in 9.441ms
Using numpy was 81.6982083869354x faster than pure Python


# Magnitude and Direction

In [57]:
# magnitude
x = np.array([[4], [3]])
print(x)
print()

print('magnitude')
print('\tusing numpy linear algebra module:', LA.norm(x))  # using built-in numpy functions
print('\tusing standard numpy functions:', np.sqrt(np.sum(x ** 2)))  # "manually" calculating the norm
print()

# unit vector
print('unit vector of x')
u = x / LA.norm(x)
print(u)
print('magnitude of u:', LA.norm(u))

[[4]
 [3]]

magnitude
	using numpy linear algebra module: 5.0
	using standard numpy functions: 5.0

unit vector of x
[[0.8]
 [0.6]]
magnitude of u: 1.0


# Dot Product

In [ ]:
v = np.array([[1], [2], [1]])
w = np.array([[3], [1], [0]])

f_result = 0
for pv, pw in zip([1, 2, 1], [3, 1, 0]):
    f_result += pv * pw

print('using python for loops:', f_result)
print('using numpy.dot:', np.dot(v.T, w)[0][0])  # using numpy.dot
print('standard numpy functions:', np.sum(v * w))

# Cross Product

In [ ]:
v = np.array([[5], [0], [0]])
w = np.array([[0], [5], [0]])

print(np.cross(v.flatten(), w.flatten()).reshape((3, 1)))